# -*- coding: utf-8 -*-
"""Exercicio-casa.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CO8utaZMM78lR3D9AesCMGJK6zjyZqQ3
"""

print("exercício com a Lu")
